// Vue/netflix-clone/src/App.vue
<template>
<div>
  <Nav />
  <Banner />
    <Row title="Trending" :fetchUrl=requests.fetchTrending :isLarge=true />
      <Row title="Top Rated" :fetchUrl=requests.fetchTopRated />
      <Row
        title="Netflix Originals"
        :fetchUrl=requests.fetchNetflixOriginals
      />
      <Row title="Action Movies" :fetchUrl=requests.fetchActionMovies />
      <Row title="Comedy Movies" :fetchUrl=requests.fetchComedyMovies />
      <Row title="Horror Movies" :fetchUrl=requests.fetchHorrorMovies />
      <Row title="Documentaries" :fetchUrl=requests.fetchDocumentaries />
      </div>
</template>

<script>
import Row from './components/Row.vue'
import Banner from './components/Banner.vue'
import Nav from './components/Nav.vue'

import requests from './api/requests' 
export default {
  name: 'App',
  components: {
    Row,Banner,Nav
  },
  data () {
    return {requests:requests};
  },
  
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  
  color: #2c3e50;
  margin-top: 60px;
  
}
body{
  margin:0;
  background-color:#111;
}
</style>

// React/src/App.js
import "./styles.css";
import Row from "./row.js";
import requests from "./requests";
import Banner from "./Banner.js";
import Nav from "./Nav.js";
export default function App() {
  return (
    <div className="App">
      <Nav />
      <Banner />
      <Row title="Trending" fetchUrl={requests.fetchTrending} isLarge={true} />
      <Row title="Top Rated" fetchUrl={requests.fetchTopRated} />
      <Row
        title="Netflix Originals"
        fetchUrl={requests.fetchNetflixOriginals}
      />
      <Row title="Action Movies" fetchUrl={requests.fetchActionMovies} />
      <Row title="Comedy Movies" fetchUrl={requests.fetchComedyMovies} />
      <Row title="Horror Movies" fetchUrl={requests.fetchHorrorMovies} />
      <Row title="Documentaries" fetchUrl={requests.fetchDocumentaries} />
    </div>
  );
}
