// Vue/netflix-clone/src/components/Banner.vue
<template>
  <header
      class="banner" 
       :style="
        {
          backgroundSize: 'cover',
          backgroundPosition: 'center center',
          backgroundImage: `url(
            'https://image.tmdb.org/t/p/original/${headMovie?.backdrop_path}'
            )`
        }
       "
      >
      <div class="banner_contents">
        <h1 class="banner_title">
          {{headMovie?.name || headMovie?.title || headMovie?.original_name}}
        </h1>
        <div class="banner_buttons">
          <button class="banner_button">Play</button>
          <button class="banner_button">My List</button>
        </div>
        <h1 class="banner_description">{{headMovie?.overview}}</h1>
      </div>
      <div class="banner-fadeBottom" />
    </header>
</template>

<script>

import axios from '../api/axios'
import requests from '../api/requests'
export default {
name: 'Banner',
data()
{
  return{
    headMovie: null
  }
},
created()
{
return axios.get(requests.fetchNetflixOriginals).then(res => {
  this.headMovie = res.data.results[
    Math.floor(Math.random() * res.data.results.length - 1)
  ]
})

}
}

</script>

<style scoped>

.banner {
  color: white;
  object-fit: contain;
  height: 448px;
}
.banner_contents {
  margin-left: 30px;
  padding-top: 140px;
  height: 190px;
}
.banner_title {
  font-size: 3rem;
  font-weight: 800;
  padding-bottom: 0.3rem;
}
.banner_description {
  widows: 45rem;
  line-height: 1.3;
  padding-top: 1rem;
  font-size: 0.8rem;
  max-width: 360px;
  height: 80px;
}
.banner_button {
  cursor: pointer;
  color: #fff;
  outline: none;
  border: none;
  font-weight: 700;
  border-radius: 0.2vw;
  padding-left: 2rem;
  padding-right: 2rem;
  padding-top: 0.5rem;
  margin-right: 1rem;
  padding-bottom: 0.5rem;
  background-color: rgba(51, 51, 51, 0.5);
}
.banner_button:hover {
  color: black;
  background-color: white;
  transition: all 0.2s;
}
.banner-fadeBottom {
  height: 7.4rem;
  background-image: linear-gradient(
    180deg,
    transparent,
    rgba(37, 37, 37, 0.61),
    #111
  );
}

</style>

// React/src/Banner.js
import React, { useEffect, useState } from "react";
import axios from "./axios";
import requests from "./requests";
import "./banner.css";
function Banner() {
  const [headMovie, setHeadMovie] = useState([]);
  useEffect(() => {
    async function fetchHeadMovieData() {
      const request = await axios.get(requests.fetchNetflixOriginals);
      setHeadMovie(
        request.data.results[
          Math.floor(Math.random() * request.data.results.length - 1)
        ]
      );
    }
    fetchHeadMovieData();
  }, []);

  return (
    <header
      className="banner"
      style={{
        backgroundSize: "cover",
        backgroundImage: `url(
          "https://image.tmdb.org/t/p/original/${headMovie?.backdrop_path}"
          )`,
        backgroundPosition: "center center"
      }}
    >
      <div className="banner_contents">
        <h1 className="banner_title">
          {headMovie?.title || headMovie?.name || headMovie?.original_name}
        </h1>
        <div className="banner_buttons">
          <button className="banner_button">Play</button>
          <button className="banner_button">My List</button>
        </div>
        <h1 className="banner_description">{headMovie?.overview}</h1>
      </div>
      <div className="banner-fadeBottom" />
    </header>
  );
}
export default Banner;
